# Basic
name:               "Creative Technology Workshop Series"

copyright:
  year:             2018
  name:             Arielle Hein

# URL
url:                "https://coloringchaos.github.io/creative-tech-workshops/"
baseurl:            "/creative-tech-workshops" # the subpath of your site, e.g. /blog


permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Upcoming"
    url:            "/upcoming"
  # - name:           "Tags"
  #   url:            "/tags"
  # - name:           "Github"
  #   url:            "https://github.com/AWEEKJ/Kiko-plus"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate

exclude:            [vendor]
